//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CQuestion", Namespace="http://schemas.datacontract.org/2004/07/Quiz.Classes.Model")]
    [System.SerializableAttribute()]
    public partial class CQuestion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Level {
            get {
                return this.LevelField;
            }
            set {
                if ((this.LevelField.Equals(value) != true)) {
                    this.LevelField = value;
                    this.RaisePropertyChanged("Level");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CPicture", Namespace="http://schemas.datacontract.org/2004/07/Quiz.Classes.Service")]
    [System.SerializableAttribute()]
    public partial class CPicture : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CPictureSet", Namespace="http://schemas.datacontract.org/2004/07/Quiz.Classes.Service")]
    [System.SerializableAttribute()]
    public partial class CPictureSet : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WindowsFormsApp1.ServiceReference1.CPicture[] PictureListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WindowsFormsApp1.ServiceReference1.CPicture[] PictureList {
            get {
                return this.PictureListField;
            }
            set {
                if ((object.ReferenceEquals(this.PictureListField, value) != true)) {
                    this.PictureListField = value;
                    this.RaisePropertyChanged("PictureList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IGame")]
    public interface IGame {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGame/GetQuestion", ReplyAction="http://tempuri.org/IGame/GetQuestionResponse")]
        WindowsFormsApp1.ServiceReference1.CQuestion GetQuestion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGame/GetQuestion", ReplyAction="http://tempuri.org/IGame/GetQuestionResponse")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.CQuestion> GetQuestionAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGameChannel : WindowsFormsApp1.ServiceReference1.IGame, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GameClient : System.ServiceModel.ClientBase<WindowsFormsApp1.ServiceReference1.IGame>, WindowsFormsApp1.ServiceReference1.IGame {
        
        public GameClient() {
        }
        
        public GameClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GameClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GameClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GameClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WindowsFormsApp1.ServiceReference1.CQuestion GetQuestion() {
            return base.Channel.GetQuestion();
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.CQuestion> GetQuestionAsync() {
            return base.Channel.GetQuestionAsync();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IPictureServer")]
    public interface IPictureServer {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPictureServer/GetPicture", ReplyAction="http://tempuri.org/IPictureServer/GetPictureResponse")]
        byte[] GetPicture();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPictureServer/GetPicture", ReplyAction="http://tempuri.org/IPictureServer/GetPictureResponse")]
        System.Threading.Tasks.Task<byte[]> GetPictureAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPictureServer/GetMetaPicture", ReplyAction="http://tempuri.org/IPictureServer/GetMetaPictureResponse")]
        WindowsFormsApp1.ServiceReference1.CPicture GetMetaPicture();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPictureServer/GetMetaPicture", ReplyAction="http://tempuri.org/IPictureServer/GetMetaPictureResponse")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.CPicture> GetMetaPictureAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPictureServer/GetPictureSet", ReplyAction="http://tempuri.org/IPictureServer/GetPictureSetResponse")]
        WindowsFormsApp1.ServiceReference1.CPictureSet GetPictureSet();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPictureServer/GetPictureSet", ReplyAction="http://tempuri.org/IPictureServer/GetPictureSetResponse")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.CPictureSet> GetPictureSetAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPictureServerChannel : WindowsFormsApp1.ServiceReference1.IPictureServer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PictureServerClient : System.ServiceModel.ClientBase<WindowsFormsApp1.ServiceReference1.IPictureServer>, WindowsFormsApp1.ServiceReference1.IPictureServer {
        
        public PictureServerClient() {
        }
        
        public PictureServerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PictureServerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PictureServerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PictureServerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public byte[] GetPicture() {
            return base.Channel.GetPicture();
        }
        
        public System.Threading.Tasks.Task<byte[]> GetPictureAsync() {
            return base.Channel.GetPictureAsync();
        }
        
        public WindowsFormsApp1.ServiceReference1.CPicture GetMetaPicture() {
            return base.Channel.GetMetaPicture();
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.CPicture> GetMetaPictureAsync() {
            return base.Channel.GetMetaPictureAsync();
        }
        
        public WindowsFormsApp1.ServiceReference1.CPictureSet GetPictureSet() {
            return base.Channel.GetPictureSet();
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.CPictureSet> GetPictureSetAsync() {
            return base.Channel.GetPictureSetAsync();
        }
    }
}
